#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DemoCheckOut.Resource", IsApplication=true)]

namespace DemoCheckOut
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public const int colorAccent = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int navigationBarColor = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int textColorPrimary = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int windowBackground = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int custom_tab_layout_height = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int tab_label = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int tab_max_width = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tab_padding_bottom = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_call = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_contacts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_favourite = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int bSubmit = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int hsvPaymentMethods = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int llPaymentTypes = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int textView1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int viewPager = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ConfirmationFragmentView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CustomViewIconTextTabs = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int OrderFragmentView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int PaymentDetailsView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int PaymentFragmentView = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_payment_type = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int ApplicationName = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Hello = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int font_fontFamily_medium = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int one = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int two = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
